# file 模块用来记录绘图的数据来源，例如 txt 文件和 xlxs 文件
# file 模块可以配置图例的文本，如果存在多个 [[file]] 默认开启子图模式
[[file]]
# 记录绘图的数据来源的 txt 文件或者 xlxs 文件的路径，推荐使用绝对路径
path = "uv.txt"
# 配置图例的文本，可以选择一个字符串类型的，也可以选择一个记录多个字符串的集合
legend = ["style: -", "style: --", "style: -.", "style: :", "style: -."]
# 配置曲线的颜色，可以选择一个字符串类型的，也可以选择一个记录多个字符串的集合
# 如果为空，则使用默认的颜色主题，其他的颜色主题可以再程序中配置
color = ["black", "red", "orange", "yellow", "blue"]
# 配置曲线的格式，可以选择一个字符串类型的，也可以选择一个记录多个字符串的集合
# 如果为空，则所有曲线都是 "-" 类型
style = ["-", "--", "-.", ":", "-."]

