# 光谱绘制的类型，可选 1. 单子图；2. 多子图。
# 如果需要绘制多子图，则需要先修改 PlotType，再将包含多子图的数据的 txt 文件文件名写在一个名为 multiple.txt 的文件中
PlotType = 2
# X 轴坐标的最小、最大值以及间距，例如 0, 4000, 500
xLimit = [0, 4000, 500]
# Y 轴坐标的最小、最大值以及间距，例如 0, 3000, 1000
yLimit = [0, 3000, 1000]
# 配图的标题，可以为空
Title = ""
# 设置 x 轴标签
xLabel = ""
# 设置 y 轴标签
yLabel = ""
# 设置全局的字体，一般为 Arail
FontFamily = "Arail"
# 设置图片的大小，也就是设置图片的长和宽
FigureSize = [8, 6]
# 曲线的颜色，可以为一个列表，优先从第一个开始选择。
# 如果开启了多子图，则每一个颜色就对应一个子图的颜色
Colors = ["black", "red", "orange", "blue"]
# 曲线的样式，可以为一个列表，优先从第一个开始选择
# 如果开启了多子图，则每一个格式就对应一个子图的格式
LineStyle = ["-", "--", "--", "--"]
# 是否显示表达式为 Y = 0 的直线，可选 0. 关闭；1. 开启
# 可以在绘制 ECD、VCD 谱时开启
ZeroLine = 0
# 选择是否显示子图的序号，只能在左上角。可选 0. 关闭；1. 开启
# 需要开启多子图才能配置
Serial = 1
# 是否显示图例，可选 0. 关闭；1. 开启
# 通常是绘制单子图的多曲线图时开启，多子图也可以开启。单子图开启时显示在图像的右上角，多子图开启时显示在图像的右边
Legend = 0
# 图例的文本，需要和 Colors 和 LineStyle 列表中元素的数量一样
LegendText = ["", "", "", ""]



