[[IR]]
path = "ir_txt/CH3CHO.txt"
size = [5, 2]
xlim = [0, 4000, 500]
ylim = [0, 3000, 1000]
style = [
    ["Acetaldehyde", "red", "-"]
]

[[IR]]
path = "ir_txt/CH3CHO.txt"
size = [5, 2]
xlim = [0, 4000, 500]
ylim = [0, 3000, 1000]
style = [
    ["acetone", "blue", "-"]
]

[[IR]]
path = "ir_txt/CH3CHO.txt"
size = [5, 2]
xlim = [0, 4000, 500]
ylim = [0, 3000, 1000]
style = [
    ["Methyl acetate", "orange", "-"]
]

[[IR]]
path = "ir_txt/CH3CHO.txt"
size = [5, 2]
xlim = [0, 4000, 500]
ylim = [0, 3000, 1000]
style = [
    ["Acetate formamide", "green", "-"]
]
