# file 模块用来记录绘图的数据来源，例如 txt 文件和 xlxs 文件
# file 模块可以配置图例的文本，如果存在多个 [[file]] 默认开启子图模式
[[file]]
# 记录绘图的数据来源的 txt 文件或者 xlxs 文件的路径，推荐使用绝对路径
path = "UV_curve.txt"
# 配置图例的文本，可以选择一个字符串类型的，也可以选择一个记录多个字符串的集合
legend = ["total", "S0->S2", "S0->S5", "S0->S11", "S0->S13"]
